export const studio = {
  hero: {
    eyebrow: "Mizan Qist Studio",
    title: "Brand, web, software and 3D, delivered by one team.",
    text: "The Studio is the creative and technology arm of Mizan Qist. We design identities, build websites and software, visualise buildings and products, and launch campaigns for businesses and individuals who care how their work looks and performs.",
    primary: { label: "Start a project", href: "#enquire" },
    secondary: { label: "See our work", href: "/studio/work" },
  },
  // SERVICE CATEGORIES — each becomes an anchored section on /studio.
  serviceCategories: [
    {
      id: "technology",
      icon: "Code2",
      title: "Technology",
      intro: "Software that is designed as carefully as it is engineered.",
      services: [
        { title: "Software development", text: "Custom platforms, internal tools and integrations built to be maintained." },
        { title: "Web development", text: "Fast, accessible marketing and content sites that rank and convert." },
        { title: "App development", text: "iOS, Android and cross-platform apps with a native feel." },
        { title: "E-commerce builds", text: "Storefronts, checkout and fulfilment flows that make buying effortless." },
      ],
    },
    {
      id: "brand",
      icon: "Palette",
      title: "Brand",
      intro: "Identities that are distinctive on day one and still right in year ten.",
      services: [
        { title: "Brand identity", text: "Full visual systems: mark, type, colour, imagery and tone of voice." },
        { title: "Logo design", text: "Marks drawn to work at every size, from favicon to signage." },
        { title: "Branding strategy", text: "Positioning, naming and messaging grounded in your market." },
        { title: "Brand guidelines", text: "Clear, practical documentation your team will actually use." },
      ],
    },
    {
      id: "visual",
      icon: "Box",
      title: "Visual & 3D",
      intro: "Photoreal visualisation and motion for architecture, products and campaigns.",
      services: [
        { title: "3D modelling", text: "Accurate models of buildings, interiors and products from drawings or sketches." },
        { title: "Architectural rendering", text: "Stills and walkthroughs that sell a development before the first brick." },
        { title: "Motion design", text: "Animated identities, explainers and social-ready motion." },
        { title: "Graphic design", text: "Campaign, digital and environmental graphics with a consistent hand." },
      ],
    },
    {
      id: "print",
      icon: "Printer",
      title: "Print & Editorial",
      intro: "Printed pieces with the weight and finish your brand deserves.",
      services: [
        { title: "Brochure design", text: "Property, corporate and product brochures, print-ready and web-ready." },
        { title: "Magazine design", text: "Editorial layouts, typography systems and cover art." },
        { title: "Menus", text: "Restaurant and café menus designed to be read, and to sell." },
        { title: "Corporate stationery", text: "Letterheads, business cards, invoices and presentation templates." },
      ],
    },
    {
      id: "launch",
      icon: "Rocket",
      title: "Launch & Marketing",
      intro: "Campaigns that give a product or opening the entrance it deserves.",
      services: [
        { title: "Product launch design", text: "Launch identities, landing pages and assets across every channel." },
        { title: "Campaigns", text: "Integrated campaigns planned, designed and produced end to end." },
        { title: "Social media content", text: "Monthly content systems with a consistent, recognisable look." },
        { title: "Marketing strategy", text: "Channel, messaging and budget planning tied to measurable goals." },
      ],
    },
  ],
  industries: [
    { icon: "Building2", title: "Real estate developers", text: "Brochures, visualisation and sales websites for developments." },
    { icon: "Ruler", title: "Architects", text: "Renders, portfolio sites and presentation decks." },
    { icon: "Scale", title: "Law firms", text: "Restrained identities and websites that convey authority." },
    { icon: "Stethoscope", title: "Dental clinics", text: "Welcoming brands, booking-ready websites and signage." },
    { icon: "UtensilsCrossed", title: "Restaurants", text: "Menus, identities and ordering-enabled websites." },
    { icon: "Scissors", title: "Barbershops", text: "Bold identities, booking pages and social content." },
    { icon: "ShoppingBag", title: "Retail", text: "E-commerce builds, packaging and campaign creative." },
    { icon: "Briefcase", title: "Corporate", text: "Stationery, reports, intranets and internal tools." },
  ],
  personal: {
    eyebrow: "Personal & celebrations",
    title: "For the moments that deserve a brand of their own.",
    text: "Not every project is a company. We bring the same care to the identities, invitations and keepsakes of personal occasions.",
    items: [
      { icon: "Heart", title: "Wedding branding", text: "Monograms, invitation suites, signage and digital invites." },
      { icon: "Cake", title: "Birthday branding", text: "Themed identities, posters and social assets for milestone birthdays." },
      { icon: "GraduationCap", title: "Graduation posters", text: "Portrait-led posters and announcements worth framing." },
      { icon: "Sparkles", title: "Event identities", text: "Naming, visuals and collateral for launches, galas and private events." },
    ],
  },
  process: [
    { step: "01", title: "Discover", text: "A short, structured conversation to understand goals, audience and constraints. You get a written brief and a fixed proposal." },
    { step: "02", title: "Design", text: "Concepts, then refinement. You see work early and often, and nothing moves forward without your sign-off." },
    { step: "03", title: "Deliver", text: "Build, test and hand over. Files, source code and documentation are yours." },
    { step: "04", title: "Support", text: "Updates, hosting guidance and a direct line to the people who built it." },
  ],
  partnerProgramme: {
    eyebrow: "Partner programme",
    title: "A quiet partnership for people who sell exceptional things.",
    text: "We work alongside real estate agents, developers, watch dealers, jewellers and car dealers to present their inventory properly and reach the right buyers. If you would like to explore a marketing partnership, we would be glad to hear from you.",
    audiences: ["Real estate agents", "Developers", "Watch dealers", "Jewellers", "Car dealers"],
    cta: { label: "Enquire about partnering", href: "/contact?division=studio&topic=partner" },
  },
  // FORM OPTIONS
  serviceTypes: [
    "Software or app development",
    "Website or e-commerce",
    "Brand identity",
    "3D and visualisation",
    "Print and editorial",
    "Launch campaign or marketing",
    "Personal or event branding",
    "Something else",
  ],
  budgets: ["Under ₦500k / £300", "₦500k – ₦1.5m / £300 – £900", "₦1.5m – ₦5m / £900 – £3k", "₦5m+ / £3k+", "Not sure yet"],
  timelines: ["As soon as possible", "Within a month", "1–3 months", "3+ months", "Flexible"],
};
